### ISSUE TITLE
Guiscrcpy crashes when started for the first time

### ISSUE THREAD

**Issue by linuxundich** [srevinsaju/guiscrcpy#10]
I tried Guiscrcpy on two systems and both times I noticed that the applications crashes the first time, when no user configuration could be found.

```
$ guiscrcpy
guiscrcpy v1.10.0-release
by srevinsaju
************************************
released on 24082019 GMT+0300 2048 
************************************
User configuration file not found!
output: <_io.BufferedReader name=16>
Traceback (most recent call last):
  File "__main__.py", line 1301, in <module>
  File "__main__.py", line 978, in __init__
NameError: name 'dimension0' is not defined
[3165] Failed to execute script __main__
```

The second time, when the basic configuration was saved, everthing is fine and the application windows appears on the screen.

```
$ guiscrcpy
guiscrcpy v1.10.0-release
by srevinsaju
************************************
released on 24082019 GMT+0300 2048 
************************************
User configuration file found!
cfg: ['#########################\n', 'Created by Srevin Saju\n', '#########################\n', '1567787607.6434782\n']
FAILED dispRO
Bitrate :  8000  + Dimensions None 
8000
dispRO: False
output: <_io.BufferedReader name=16>
OPTS: 8000 None False False False
SCRCPY RUNNING
POSITION OF PANEL:
self.oldpos PyQt5.QtCore.QPoint()
FINE TILL HERE
Class entered : MyAppv

```

**Comment by srevinsaju** [comment]
@linuxundich, may I know which guiscrcpy version you are using? Seems like I had formatted the output in the latest release?
Please check if you are using v1.10.1 release and check if you are using source or binary
