### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'guiscrcpy.platform'

### ISSUE THREAD

**Issue by yochananmarqos** [srevinsaju/guiscrcpy#163]
**Describe the bug**

Perhaps you weren't done yet, but I just tested the changes since I saw you were preparing for 4.3.

```
Traceback (most recent call last):
  File "/usr/sbin/guiscrcpy", line 33, in <module>
    sys.exit(load_entry_point('guiscrcpy==4.3.0.dev0', 'console_scripts', 'guiscrcpy')())
  File "/usr/sbin/guiscrcpy", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/guiscrcpy/cli.py", line 8, in <module>
    from .lib.utils import format_colors as fc
  File "/usr/lib/python3.8/site-packages/guiscrcpy/lib/utils.py", line 28, in <module>
    from guiscrcpy.platform.platform import System
ModuleNotFoundError: No module named 'guiscrcpy.platform'
```

**Desktop:**

```
██████████████████  ████████   yochanan@inspirognome 
██████████████████  ████████   --------------------- 
██████████████████  ████████   OS: Manjaro Linux x86_64 
██████████████████  ████████   Host: Inspiron 5575 1.3.3 
████████            ████████   Kernel: 5.8.5-2-MANJARO 
████████  ████████  ████████   Uptime: 1 hour, 6 mins 
████████  ████████  ████████   Packages: 1890 (pacman) 
████████  ████████  ████████   Shell: zsh 5.8 
████████  ████████  ████████   Resolution: 1920x1080 
████████  ████████  ████████   DE: GNOME 3.36.5 
████████  ████████  ████████   WM: Mutter 
████████  ████████  ████████   WM Theme: Adwaita 
████████  ████████  ████████   Theme: Adwaita-maia-dark [GTK2/3] 
████████  ████████  ████████   Icons: Papirus-Dark-Maia [GTK2/3] 
                               Terminal: tilix 
                               CPU: AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx (8) @ 2.000GHz 
                               GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series 
                               Memory: 6055MiB / 15715MiB
```

**Comment by srevinsaju** [comment]
Thanks @yochananmarqos for testing. Can you please show me the directory structure for 
`/usr/lib/python3.8/site-packages/guiscrcpy`

```bash
ls /usr/lib/python3.8/site-packages/guiscrcpy
```

**Comment by yochananmarqos** [comment]
```
❯ tree /usr/lib/python3.8/site-packages/guiscrcpy
/usr/lib/python3.8/site-packages/guiscrcpy
├── cli.py
├── constants.py
├── __init__.py
├── install
│   ├── finder.py
│   ├── __init__.py
│   └── __pycache__
│       ├── finder.cpython-38.opt-1.pyc
│       ├── finder.cpython-38.pyc
│       ├── __init__.cpython-38.opt-1.pyc
│       └── __init__.cpython-38.pyc
├── launcher.py
├── lib
│   ├── check.py
│   ├── config.py
│   ├── __init__.py
│   ├── mapper
│   │   ├── __init__.py
│   │   ├── mapper.py
│   │   ├── __pycache__
│   │   │   ├── __init__.cpython-38.opt-1.pyc
│   │   │   ├── __init__.cpython-38.pyc
│   │   │   ├── mapper.cpython-38.opt-1.pyc
│   │   │   ├── mapper.cpython-38.pyc
│   │   │   ├── ux.cpython-38.opt-1.pyc
│   │   │   └── ux.cpython-38.pyc
│   │   └── ux.py
│   ├── process.py
│   ├── __pycache__
│   │   ├── check.cpython-38.opt-1.pyc
│   │   ├── check.cpython-38.pyc
│   │   ├── config.cpython-38.opt-1.pyc
│   │   ├── config.cpython-38.pyc
│   │   ├── __init__.cpython-38.opt-1.pyc
│   │   ├── __init__.cpython-38.pyc
│   │   ├── process.cpython-38.opt-1.pyc
│   │   ├── process.cpython-38.pyc
│   │   ├── toolkit.cpython-38.opt-1.pyc
│   │   ├── toolkit.cpython-38.pyc
│   │   ├── utils.cpython-38.opt-1.pyc
│   │   └── utils.cpython-38.pyc
│   ├── toolkit.py
│   └── utils.py
├── __main__.py
├── __pycache__
│   ├── cli.cpython-38.opt-1.pyc
│   ├── cli.cpython-38.pyc
│   ├── constants.cpython-38.opt-1.pyc
│   ├── constants.cpython-38.pyc
│   ├── __init__.cpython-38.opt-1.pyc
│   ├── __init__.cpython-38.pyc
│   ├── launcher.cpython-38.opt-1.pyc
│   ├── launcher.cpython-38.pyc
│   ├── __main__.cpython-38.opt-1.pyc
│   ├── __main__.cpython-38.pyc
│   ├── version.cpython-38.opt-1.pyc
│   └── version.cpython-38.pyc
├── settings
│   ├── __init__.py
│   ├── __pycache__
│   │   ├── __init__.cpython-38.opt-1.pyc
│   │   ├── __init__.cpython-38.pyc
│   │   ├── settings.cpython-38.opt-1.pyc
│   │   └── settings.cpython-38.pyc
│   └── settings.py
├── ux
│   ├── initializer.py
│   ├── __init__.py
│   ├── network.py
│   ├── panel.py
│   ├── __pycache__
│   │   ├── __init__.cpython-38.opt-1.pyc
│   │   ├── __init__.cpython-38.pyc
│   │   ├── initializer.cpython-38.opt-1.pyc
│   │   ├── initializer.cpython-38.pyc
│   │   ├── network.cpython-38.opt-1.pyc
│   │   ├── network.cpython-38.pyc
│   │   ├── panel.cpython-38.opt-1.pyc
│   │   ├── panel.cpython-38.pyc
│   │   ├── settings.cpython-38.opt-1.pyc
│   │   ├── settings.cpython-38.pyc
│   │   ├── swipe.cpython-38.opt-1.pyc
│   │   ├── swipe.cpython-38.pyc
│   │   ├── toolkit.cpython-38.opt-1.pyc
│   │   └── toolkit.cpython-38.pyc
│   ├── settings.py
│   ├── swipe.py
│   └── toolkit.py
└── version.py

11 directories, 78 files
```

**Comment by srevinsaju** [comment]
Thanks a lot, looks like I had something cached during testing. I will quickly push a fix

**Comment by srevinsaju** [comment]
@yochananmarqos can you please test on master again? Thanks a lot again!! :smile:

**Comment by yochananmarqos** [comment]
That did the trick, 4.3 is looking good. :+1:
