### ISSUE TITLE
[BUG] Unable to Refresh Network Devices on MacOS 10.15.6 (Catalina)

### ISSUE THREAD

**Issue by raman325** [srevinsaju/guiscrcpy#164]
**Describe the bug**
When attempting to refresh network devices, the program crashes with the following errors in Terminal:
```
Process Process-232:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 99, in run
  File "/usr/local/lib/python3.7/site-packages/guiscrcpy/network/network.py", line 27, in pinger
OSError: [Errno 24] Too many open files: '/dev/null'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/guiscrcpy/ux/network.py", line 117, in refresh
    self.listView.addItems(self.nm.map_network())
  File "/usr/local/lib/python3.7/site-packages/guiscrcpy/network/network.py", line 88, in map_network
    p.start()
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/popen_fork.py", line 69, in _launch
    parent_r, child_w = os.pipe()
OSError: [Errno 24] Too many open files
Abort trap: 6
```

**To Reproduce**
1. Go to Network Manager
2. Click on Refresh
3. Wait for program to crash

**Expected behavior**
Network devices are discovered

**Desktop (please complete the following information):**
* [x] MacOS
 - **Version**: Catalina 10.15.6

**Additional context**

**Comment by srevinsaju** [comment]
Thanks for reporting. Multiprocessing (aka Semaphores) doesn't work on macOS due to its unusual over-security. I might not be able to scan for open ports on your local network. But thanks again. I guess its better to show an error message instead of crashing like this.

Does connect directly by IP address work on macOS? I have not heard how it works on macOS from other developers. 
We have a development Discord server, if you are interested to join: https://discord.gg/mFqj3a5

I also have the infrastructure to build macOS DMGs, but we don't have testers

**Comment by srevinsaju** [comment]
@raman325 May I know why the issue was closed?

**Comment by raman325** [comment]
I saw a bunch of Python processes still running - once I killed them and restarted the GUI, the issue went away. Since that appeared to be related to too many processes being open, the PR I submitted should prevent this particular issue

**Comment by srevinsaju** [comment]
I will link this issue to your open PR, so this issue will be closed when your PR is merged. :tada:
