### ISSUE TITLE
[BUG]PermissionError: [WinError 5] Access is denied

### ISSUE THREAD

**Issue by sqr101** [srevinsaju/guiscrcpy#183]
**Describe the bug**
guiscrcpy.exe won't start

**To Reproduce**
run guiscrcpy.exe
error
`Traceback (most recent call last):
  File "C:\Users\princ\AppData\Roaming\Python\Python36\site-packages\guiscrcpy\cli.py", line 112, in cli
    debug__no_scrcpy=debug__disable_scrcpy)
  File "C:\Users\princ\AppData\Roaming\Python\Python36\site-packages\guiscrcpy\launcher.py", line 1259, in bootstrap
    panels_not_always_on_top=not aot, debug__no_scrcpy=debug__no_scrcpy
  File "C:\Users\princ\AppData\Roaming\Python\Python36\site-packages\guiscrcpy\launcher.py", line 206, in __init__
    self.refresh_devices()
  File "C:\Users\princ\AppData\Roaming\Python\Python36\site-packages\guiscrcpy\launcher.py", line 228, in refresh_devices
    self.scan_devices_update_list_view()
  File "C:\Users\princ\AppData\Roaming\Python\Python36\site-packages\guiscrcpy\launcher.py", line 611, in scan_devices_update_list_view
    __devices = self.adb.devices_detailed()
  File "C:\Users\princ\AppData\Roaming\Python\Python36\site-packages\guiscrcpy\lib\check.py", line 211, in devices_detailed
    proc = Popen(_(self.path + " devices -l"), stdout=PIPE)
  File "c:\program files\python36\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "c:\program files\python36\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
PermissionError: [WinError 5] Access is denied`

**Desktop (please complete the following information):**
* [ ] Windows
- **Architecture**: 64-bit
- **Version**: 10

**Comment by srevinsaju** [comment]
@sqr101 Did you install with `pip`?

**Comment by srevinsaju** [comment]
Awaiting response. Closing
