### ISSUE TITLE
Have to install pywin32 manually on windows [BUG]

### ISSUE THREAD

**Issue by ajdjyt** [srevinsaju/guiscrcpy#187]
**Describe the bug**
Ive had to install the pywin32 package manually on both windows systems i have tried guiscrcpy on.
**To Reproduce**
1. install Guiscrcpy on windows - "pip install -u guiscrcpy"
2. Run guiscrcpy, get the error - "No module named win32com"
**Expected behavior**
That pywin32 is installed by guiscrcpy 
**Screenshots**
https://imgur.com/a/xv06aqR
**Desktop (please complete the following information):**
[.]Windows
Windows 10 2004 64 bit
[] Linux
Worked fine on linux

**Comment by srevinsaju** [comment]
Weird, I thought it should have been installed automatically. Thanks for reporting anyway. I will find a fix.

**Comment by srevinsaju** [comment]
@ajdjyt Can you sent me the exact traceback, i.e which line causes the error?

**Comment by ajdjyt** [comment]
Traceback (most recent call last):
  File "c:\users\ajdj\appdata\local\programs\python\python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\ajdj\appdata\local\programs\python\python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\AjDj\AppData\Local\Programs\Python\Python38-32\Scripts\guiscrcpy.exe\__main__.py", line 4, in <module>
  File "c:\users\ajdj\appdata\local\programs\python\python38-32\lib\site-packages\guiscrcpy\cli.py", line 11, in <module>
    from .lib.utils import format_colors as fc, show_message_box
  File "c:\users\ajdj\appdata\local\programs\python\python38-32\lib\site-packages\guiscrcpy\lib\utils.py", line 30, in <module>
    from ..platform.platform import System
  File "c:\users\ajdj\appdata\local\programs\python\python38-32\lib\site-packages\guiscrcpy\platform\platform.py", line 25, in <module>
    from guiscrcpy.platform.windows import Windows as System
  File "c:\users\ajdj\appdata\local\programs\python\python38-32\lib\site-packages\guiscrcpy\platform\windows.py", line 23, in <module>
    from guiscrcpy.platform.windows_tools.tools import make_shortcut
  File "c:\users\ajdj\appdata\local\programs\python\python38-32\lib\site-packages\guiscrcpy\platform\windows_tools\tools.py", line 10, in <module>
    import win32com.client
ModuleNotFoundError: No module named 'win32com'

**Comment by srevinsaju** [comment]
Thanks :+1:

**Comment by srevinsaju** [comment]
Fixed

**Comment by azumukupoe** [comment]
I still have this issue

**Comment by BlacRyu** [comment]
I had the same problem here.
guiscrcpy v4.10.0
Win10 Pro x64 
```λ guiscrcpy
Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\guiscrcpy.exe\__main__.py", line 4, in <module>
  File "c:\python39\lib\site-packages\guiscrcpy\cli.py", line 12, in <module>
    from .lib.utils import format_colors as fc, show_message_box
  File "c:\python39\lib\site-packages\guiscrcpy\lib\utils.py", line 31, in <module>
    from ..platform.platform import System
  File "c:\python39\lib\site-packages\guiscrcpy\platform\platform.py", line 25, in <module>
    from guiscrcpy.platform.windows import Windows as System
  File "c:\python39\lib\site-packages\guiscrcpy\platform\windows.py", line 23, in <module>
    from guiscrcpy.platform.windows_tools.tools import make_shortcut
  File "c:\python39\lib\site-packages\guiscrcpy\platform\windows_tools\tools.py", line 10, in <module>
    import win32com.client
ModuleNotFoundError: No module named 'win32com'
