### ISSUE TITLE
[BUG] in Windows 10 - Launch error

### ISSUE THREAD

**Issue by scropion86** [srevinsaju/guiscrcpy#220]
**Describe the bug**

**To Reproduce**
1. download the latest stable windows version from website "https://github.com/srevinsaju/guiscrcpy/releases/download/3.0/guiscrcpy-3.0-win-compiled.zip"
2. extract and run the exe file
3. CMD pop up and close 
4. run the exe from CMD manually 
5. you have below error

```
D:\guiscrcpy-3.0-win-compiled>guiscrcpy
Traceback (most recent call last):
  File "site-packages\git\__init__.py", line 83, in <module>
  File "site-packages\git\__init__.py", line 73, in refresh
  File "site-packages\git\cmd.py", line 287, in refresh
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "guiscrcpy", line 3, in <module>
  File "C:\Users\SS\AppData\Local\Programs\Python\Python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
  File "guiscrcpy\launcher.py", line 51, in <module>
  File "C:\Users\SS\AppData\Local\Programs\Python\Python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
  File "guiscrcpy\lib\ver.py", line 24, in <module>
  File "C:\Users\SS\AppData\Local\Programs\Python\Python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
  File "site-packages\git\__init__.py", line 85, in <module>
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

[3168] Failed to execute script guiscrcpy

D:\guiscrcpy-3.0-win-compiled>
```

**Expected behavior**
ask for the ADB location and scrpy after that

**Desktop (please complete the following information):**
* [ ] Windows 10 Pro 20H2
- **Architecture**: 64-bit
- **OS build**: 19042.804 - Windows Feature Experience Pack 120.2212.551.0

**Additional context**

scrcpy-win64-v1.17
guiscrcpy-3.0-win

**Comment by srevinsaju** [comment]
You are using an old version (3.0.0). The latest version is over here : https://github.com/srevinsaju/guiscrcpy/releases/latest
