### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MBechirM** [srevinsaju/guiscrcpy#230]
**Describe the bug**
everytime I run the program I get this error :

Traceback (most recent call last):
  File "guiscrcpy\cli.py", line 156, in cli
  File "guiscrcpy\lib\config.py", line 58, in __init__
  File "guiscrcpy\lib\config.py", line 61, in load_config
  File "guiscrcpy\lib\config.py", line 144, in check_file
  File "guiscrcpy\lib\config.py", line 131, in read_file
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**To Reproduce**
1. Open guiscrcpy.exe
2. See error

**Expected behavior**
the program to run as usual

**Screenshots**
![image](https://user-images.githubusercontent.com/32303019/112746733-bc380e00-8fa8-11eb-804d-3d202e41a28b.png)

**Desktop (please complete the following information):**
* [ ] Windows
- **Architecture**: 64-bit
- **Version**: 10

**Additional context**

**Comment by srevinsaju** [comment]
just do `./guiscrcpy.exe config -r ` on a command prompt, and that would do :D

**Comment by MBechirM** [comment]
thank you so much, it was very frustrating
