### ISSUE TITLE
setup.py build errors

### ISSUE THREAD

**Issue by yochananmarqos** [srevinsaju/guiscrcpy#24]
I'm the AUR maintainer for both packages, as you may already know. I'm using Manjaro GNOME.

Building from v2.0 release tarball:
```
Traceback (most recent call last):
  File "setup.py", line 18, in <module>
    version = repo.git.describe("--tags")[:-9],
  File "/usr/lib/python3.7/site-packages/git/cmd.py", line 547, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/git/cmd.py", line 1016, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/usr/lib/python3.7/site-packages/git/cmd.py", line 827, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git describe --tags
  stderr: 'fatal: No names found, cannot describe anything.'
```

This also happened with v1.12.0, but not v1.11.3. I cannot reproduce it building from c6169d4.

**Comment by srevinsaju** [comment]
I suggest you to clone the repo than building from tarball

**Comment by yochananmarqos** [comment]
Well, there's no point in the `guiscrcpy` AUR package then. I'll continue to maintain the `guiscrcpy-gt` package.
