### ISSUE TITLE
[BUG] can not  run on windos 11

### ISSUE THREAD

**Issue by coderstory** [srevinsaju/guiscrcpy#265]
**Describe the bug**
guiscrcpy-PyQt5-x64.exe 
lastest version  from github release

C:\Users\Administrator>D:\Data\Downloads\guiscrcpy-PyQt5-x64.exe
Traceback (most recent call last):
  File "entry.py", line 1, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "guiscrcpy\cli.py", line 12, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "guiscrcpy\lib\utils.py", line 31, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "guiscrcpy\platform\platform.py", line 25, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "guiscrcpy\platform\windows.py", line 23, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "guiscrcpy\platform\windows_tools\tools.py", line 10, in <module>
ModuleNotFoundError: No module named 'win32com'
[12100] Failed to execute script 'entry' due to unhandled exception!

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
* [ ] Windows
- **Architecture**:  64-bit
- **Version**:  11

**Comment by SonaliBendre** [comment]
try pyside2
