### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'PySide'

### ISSUE THREAD

**Issue by jisungbin** [srevinsaju/guiscrcpy#293]
## OS

MacOS Monterey 12.2

---

When I run `guiscrcpy` I get the error `ModuleNotFoundError: No module named 'PySide'.` So, I tried to install `PySide` like this:
```
pip install pyside
```

But this throws an error
```
Collecting pyside
  Using cached PySide-1.2.4.tar.gz (9.3 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      only these python versions are supported: [(2, 6), (2, 7), (3, 2), (3, 3), (3, 4)]
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
I tried installing a different version of `PySide`, it installed but still `guiscrcpy` does not run.
What should I do?

**Comment by srevinsaju** [comment]
You should actually install `PySide2`, not `PySide`.

**Comment by jisungbin** [comment]
I tried to install `PySide2`, but I still get an installation error.
```
ERROR: Could not find a version that satisfies the requirement pyside2 (from versions: none)
ERROR: No matching distribution found for pyside2
```
But thanks for the help!

**Comment by gouravkhunger** [comment]
Are you also on M1? I also had errors with python 3.9 and above. Python 3.8 works fine.

[Here](https://github.com/srevinsaju/guiscrcpy/blob/main/docs/BUILD.md#m1-specific-build-instructions) are the workaround instructions for m1 for now.

**Comment by jisungbin** [comment]
Wow, I'm M1 right! thanks 😘

**Comment by gouravkhunger** [comment]
great, happy to help 😄

**Comment by jisungbin** [comment]
@gouravkhunger I thought I was successful, but didn't! This time the following the below error:
```
ERROR:root:MacOS is untested. guiscrcpy is trying to use Linux config on Mac
```

**Comment by gouravkhunger** [comment]
That's a warning more than an error 🤔 
[I got that same log](https://youtu.be/JsqV5QJQ0Y4?t=279). It took a minute or two but ran successfully at the end :)

**Comment by jisungbin** [comment]
wow again!! Thank you so much, I'm really going to close this issue now.

**Comment by gouravkhunger** [comment]
sure, if you need help feel free to open it or create a new one!

**Comment by srevinsaju** [comment]
Thanks @gouravkhunger for the help! :rocket: :heart:

**Comment by lamyergeier** [comment]
@gouravkhunger @srevinsaju  I am using Intel MAC. Any suggestions?

```
$ brew install pyqt
Warning: pyqt 6.3.1 is already installed and up-to-date.
To reinstall 6.3.1, run:
  brew reinstall pyqt

$ brew install pyside@2
Warning: pyside@2 5.15.5_2 is already installed and up-to-date.
To reinstall 5.15.5_2, run:
  brew reinstall pyside@2

$ pip3 install guiscrcpy --user
Requirement already satisfied: guiscrcpy in /Users/lamyergeier/Library/Python/3.8/lib/python/site-packages (2022.6.1)
Requirement already satisfied: coloredlogs<16.0.0,>=15.0.1 in /Users/lamyergeier/Library/Python/3.8/lib/python/site-packages (from guiscrcpy) (15.0.1)
Requirement already satisfied: colorama<0.5.0,>=0.4.4 in /Users/lamyergeier/Library/Python/3.8/lib/python/site-packages (from guiscrcpy) (0.4.5)
Requirement already satisfied: QtPy<2.0.0,>=1.9.0 in /Users/lamyergeier/Library/Python/3.8/lib/python/site-packages (from guiscrcpy) (1.11.3)
Requirement already satisfied: CairoSVG<3.0.0,>=2.5.2 in /Users/lamyergeier/Library/Python/3.8/lib/python/site-packages (from guiscrcpy) (2.5.2)
Requirement already satisfied: black==22.3.0 in /Users/lamyergeier/Library/Python/3.8/lib/python/site-packages (from guiscrcpy) (22.3.0)
Requirement already satisfied: psutil<6.0.0,>=5.8.0 in /Users/lamyergeier/Library/Python/3.8/lib/python/site-packages (from guiscrcpy) (5.9.1)
Requirement already satisfied: click<9.0.0,>=8.0.1 in /Users/lamyergeier/Library/Python/3.8/lib/python/site-packages (from guiscrcpy) (8.1.3)
Requirement already satisfied: pynput==1.6.8 in /Users/lamyergeier/Library/Python/3.8/lib/python/site-packages (from guiscrcpy) (1.6.8)
Requirement already satisfied: pathspec>=0.9.0 in /Users/lamyergeier/Library/Python/3.8/lib/python/site-packages (from black==22.3.0->guiscrcpy) (0.9.0)
Requirement already satisfied: tomli>=1.1.0 in /Users/lamyergeier/Library/Python/3.8/lib/python/site-packages (from black==22.3.0->guiscrcpy) (2.0.1)
Requirement already satisfied: typing-extensions>=3.10.0.0 in /Users/lamyergeier/Library/Python/3.8/lib/python/site-packages (from black==22.3.0->guiscrcpy) (4.3.0)
Requirement already satisfied: mypy-extensions>=0.4.3 in /Users/lamyergeier/Library/Python/3.8/lib/python/site-packages (from black==22.3.0->guiscrcpy) (0.4.3)
Requirement already satisfied: platformdirs>=2 in /Users/lamyergeier/Library/Python/3.8/lib/python/site-packages (from black==22.3.0->guiscrcpy) (2.5.2)
Requirement already satisfied: pyobjc-framework-Quartz>=3.0 in /Users/lamyergeier/Library/Python/3.8/lib/python/site-packages (from pynput==1.6.8->guiscrcpy) (8.5)
Requirement already satisfied: six in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages (from pynput==1.6.8->guiscrcpy) (1.15.0)
Requirement already satisfied: tinycss2 in /Users/lamyergeier/Library/Python/3.8/lib/python/site-packages (from CairoSVG<3.0.0,>=2.5.2->guiscrcpy) (1.1.1)
Requirement already satisfied: defusedxml in /Users/lamyergeier/Library/Python/3.8/lib/python/site-packages (from CairoSVG<3.0.0,>=2.5.2->guiscrcpy) (0.7.1)
Requirement already satisfied: cssselect2 in /Users/lamyergeier/Library/Python/3.8/lib/python/site-packages (from CairoSVG<3.0.0,>=2.5.2->guiscrcpy) (0.6.0)
Requirement already satisfied: pillow in /Users/lamyergeier/Library/Python/3.8/lib/python/site-packages (from CairoSVG<3.0.0,>=2.5.2->guiscrcpy) (9.2.0)
Requirement already satisfied: cairocffi in /Users/lamyergeier/Library/Python/3.8/lib/python/site-packages (from CairoSVG<3.0.0,>=2.5.2->guiscrcpy) (1.3.0)
Requirement already satisfied: humanfriendly>=9.1 in /Users/lamyergeier/Library/Python/3.8/lib/python/site-packages (from coloredlogs<16.0.0,>=15.0.1->guiscrcpy) (10.0)
Requirement already satisfied: pyobjc-core>=8.5 in /Users/lamyergeier/Library/Python/3.8/lib/python/site-packages (from pyobjc-framework-Quartz>=3.0->pynput==1.6.8->guiscrcpy) (8.5)
Requirement already satisfied: pyobjc-framework-Cocoa>=8.5 in /Users/lamyergeier/Library/Python/3.8/lib/python/site-packages (from pyobjc-framework-Quartz>=3.0->pynput==1.6.8->guiscrcpy) (8.5)
Requirement already satisfied: cffi>=1.1.0 in /Users/lamyergeier/Library/Python/3.8/lib/python/site-packages (from cairocffi->CairoSVG<3.0.0,>=2.5.2->guiscrcpy) (1.15.1)
Requirement already satisfied: webencodings in /Users/lamyergeier/Library/Python/3.8/lib/python/site-packages (from cssselect2->CairoSVG<3.0.0,>=2.5.2->guiscrcpy) (0.5.1)
Requirement already satisfied: pycparser in /Users/lamyergeier/Library/Python/3.8/lib/python/site-packages (from cffi>=1.1.0->cairocffi->CairoSVG<3.0.0,>=2.5.2->guiscrcpy) (2.21)
```

```
$ ./guiscrcpy 
Traceback (most recent call last):
  File "/Users/lamyergeier/Library/Python/3.8/lib/python/site-packages/qtpy/__init__.py", line 218, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./guiscrcpy", line 5, in <module>
    from guiscrcpy.cli import cli
  File "/Users/lamyergeier/Library/Python/3.8/lib/python/site-packages/guiscrcpy/cli.py", line 9, in <module>
    from qtpy.QtWidgets import QApplication
  File "/Users/lamyergeier/Library/Python/3.8/lib/python/site-packages/qtpy/__init__.py", line 224, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found
```
