### ISSUE TITLE
[BUG] Pyside6 not calling scrcpy and failing

### ISSUE THREAD

**Issue by Tequeromtv** [srevinsaju/guiscrcpy#300]
I received this Issue while trying to run the new released version 6 of the pyside, the scrcpy doesn't run at all and the gui just get invisible 

*Traceback (most recent call last):
  File "guiscrcpy\launcher.py", line 557, in tcpip_paired_device
  File "guiscrcpy\lib\bridge\adb.py", line 110, in tcpip
  File "subprocess.py", line 349, in call
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1360, in _execute_child
  File "subprocess.py", line 565, in list2cmdline
  File "os.py", line 822, in fsdecode
TypeError: expected str, bytes or os.PathLike object, not int

**Comment by srevinsaju** [comment]
Attempted a fix in 59ec81f, let me know if that doesn't work.
