### ISSUE TITLE
[BUG] File "/bin/guiscrcpy", line 5, in <module>

### ISSUE THREAD

**Issue by gyurmogyuri** [srevinsaju/guiscrcpy#308]
**Describe the bug**
Traceback (most recent call last):
  File "/bin/guiscrcpy", line 5, in <module>
    from guiscrcpy.cli import cli
  File "/usr/lib/python3.10/site-packages/guiscrcpy/cli.py", line 13, in <module>
    from .launcher import bootstrap
  File "/usr/lib/python3.10/site-packages/guiscrcpy/launcher.py", line 63, in <module>
    from .ux import Ui_MainWindow
  File "/usr/lib/python3.10/site-packages/guiscrcpy/ux/__init__.py", line 24, in <module>
    from guiscrcpy.ui.pyside.main import Ui_MainWindow  # noqa: F401
  File "/usr/lib/python3.10/site-packages/guiscrcpy/ui/pyside/main.py", line 11, in <module>
    from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
ImportError: /usr/lib/libpyside6.cpython-310-aarch64-linux-gnu.so.6.3: undefined symbol: _ZN9QtPrivate19QByteArrayList_joinEPK5QListI10QByteArrayEPKcx, version Qt_6

**To Reproduce**
start in Konsole

guiscrcpy-git-4.12.1.r1321.g97c0bcd-1
aarch64 aur

**Comment by srevinsaju** [comment]
Looks like something only on Arch. Please try updating to the latest version, or build from source.
