### ISSUE TITLE
[FR] Installation using pipx

### ISSUE THREAD

**Issue by lamyergeier** [srevinsaju/guiscrcpy#323]
**Is your feature request related to a problem? Please describe.**

Tried installing using [[pypa/pipx: Install and Run Python Applications in Isolated Environments](https://github.com/pypa/pipx)](https://github.com/pypa/pipx) on MacOS 12 (Intel MAC)

```
$ pipx install guiscrcpy  --force
Installing to existing venv 'guiscrcpy'
  installed package guiscrcpy 4.12.0, installed using Python 3.10.5
  These apps are now globally available
    - guiscrcpy
done! ✨ 🌟 ✨
$ guiscrcpy 
Traceback (most recent call last):
  File "/Users/lamyergeier/.local/bin/guiscrcpy", line 5, in <module>
    from guiscrcpy.cli import cli
  File "/Users/lamyergeier/.local/pipx/venvs/guiscrcpy/lib/python3.10/site-packages/guiscrcpy/cli.py", line 9, in <module>
    from qtpy.QtWidgets import QApplication
  File "/Users/lamyergeier/.local/pipx/venvs/guiscrcpy/lib/python3.10/site-packages/qtpy/QtWidgets.py", line 14, in <module>
    from PyQt5.QtWidgets import *
ModuleNotFoundError: No module named 'PyQt5'
```

---

What should I do?

**Comment by srevinsaju** [comment]
@lamyergeier ```bash 
pip install PyQt5
```
