### ISSUE TITLE
[BUG] Just doesn't work

### ISSUE THREAD

**Issue by roidy** [srevinsaju/guiscrcpy#358]
Traceback (most recent call last):
  File "guiscrcpy\cli.py", line 157, in cli
  File "guiscrcpy\launcher.py", line 1287, in bootstrap
  File "guiscrcpy\launcher.py", line 210, in __init__
  File "guiscrcpy\launcher.py", line 232, in refresh_devices
  File "guiscrcpy\launcher.py", line 631, in scan_devices_update_list_view
  File "guiscrcpy\lib\bridge\adb.py", line 123, in devices_detailed
  File "guiscrcpy\lib\utils.py", line 169, in open_process
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child
OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by jackprastna** [comment]
open cmd in the directory that guiscrcpy in, and then "(guiscrcpy.exe) config -r"
