### ISSUE TITLE
BUG guiscrcpy report

### ISSUE THREAD

**Issue by jbxxs** [srevinsaju/guiscrcpy#368]
**Describe the bug**
No conda env active, defaulting to base

guiscrcpy v2023.1.1
by @srevinsaju
https://github.com/srevinsaju/guiscrcpy

Traceback (most recent call last):
  File "guiscrcpy\cli.py", line 157, in cli
  File "guiscrcpy\launcher.py", line 1287, in bootstrap
  File "guiscrcpy\launcher.py", line 210, in __init__
  File "guiscrcpy\launcher.py", line 232, in refresh_devices
  File "guiscrcpy\launcher.py", line 631, in scan_devices_update_list_view
  File "guiscrcpy\lib\bridge\adb.py", line 123, in devices_detailed
  File "guiscrcpy\lib\utils.py", line 169, in open_process
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child

**Desktop (please complete the following information):**
* Windows 10
- **Architecture**: 64-bit
- **Version**: 2023.1.1

**Comment by J-FIRE** [comment]
I just got the same error, don't know what's causing it

**Comment by srevinsaju** [comment]
the error is likely because the right scrcpy binary was not selected. you may confirm this by checking the configuration file.

**Comment by jackprastna** [comment]
open cmd in the directory that guiscrcpy in, and then "(guiscrcpy.exe) config -r"

**Comment by Alextine** [comment]
> open cmd in the directory that guiscrcpy in, and then "(guiscrcpy.exe) config -r"

 it's working again. Thankss
