### ISSUE TITLE
[BUG] ModuleNotFoundError coloredlogs, but python-coloredlogs is installed

### ISSUE THREAD

**Issue by moshpirit** [srevinsaju/guiscrcpy#381]
**Describe the bug**
I can't run GUIscrcpy. I find this error: 
```
Traceback (most recent call last):
  File "/usr/bin/guiscrcpy", line 5, in <module>
    from guiscrcpy.cli import cli
  File "/usr/lib/python3.11/site-packages/guiscrcpy/cli.py", line 12, in <module>
    from .lib.utils import format_colors as fc, show_message_box
  File "/usr/lib/python3.11/site-packages/guiscrcpy/lib/utils.py", line 26, in <module>
    from ..logging import make_logger
  File "/usr/lib/python3.11/site-packages/guiscrcpy/logging.py", line 4, in <module>
    import coloredlogs
ModuleNotFoundError: No module named 'coloredlogs'
```

I have installed the module as a dependency through AUR (`python-coloredlogs`), and later, just in case also [through pip3](https://pastes.io/raw/lfj6teipio), yet the error persists. I must say, I'm not sure of how Python dependencies and pip work, it's still very new for me.

**To Reproduce**
1. Open a terminal
2. type `guiscrcpy` and press enter
3. See error

**Expected behavior**
The program runs

```
                   -`                    
                  .o+`                   
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: 82SV Yoga Slim 7 Pro 14IAP7 
               `+oooooo:                 Kernel: 6.4.12-arch1-1 
               -+oooooo+:                Uptime: 5 days, 11 hours, 3 mins 
             `/:-:++oooo+:               Packages: 1593 (pacman), 9 (flatpak) 
            `/++++/+++++++:              Shell: bash 5.1.16 
           `/++++++++++++++:             Resolution: 2240x1400 
          `/+++ooooooooooooo/`           DE: Plasma 5.27.7 
         ./ooosssso++osssssso+`          WM: KWin 
        .oossssso-````/ossssss+`         Theme: [Plasma], Breeze-Dark [GTK2/3] 
       -osssssso.      :ssssssso.        Icons: [Plasma], breeze-dark [GTK2/3] 
      :osssssss/        osssso+++.       Terminal: konsole 
     /ossssssss/        +ssssooo/-       Terminal Font: LiterationMono Nerd Font 11 
   `/ossssso+/:-        -:/+osssso+-     CPU: 12th Gen Intel i5-1240P (16) @ 4.400GHz 
  `+sso+:-`                 `.-/+oso:    GPU: Intel Alder Lake-P 
 `++:.                           `-/+/   Memory: 4236MiB / 7668MiB 
 .`                                 `/
```

**Comment by moshpirit** [comment]
Can it be due to the python version being 3.11.5?

**Comment by moshpirit** [comment]
Using a dedicated environment worked:

```
virtualenv -p python3 guiscrcpy-env
source guiscrcpy-env/bin/activate
guiscrcpy
```
