### ISSUE TITLE
[BUG] "START SCRCPY" crashes the app

### ISSUE THREAD

**Issue by denisapain** [srevinsaju/guiscrcpy#382]
**Describe the bug**
Clicking "START SCRCPY"

**To Reproduce**
1. Install GUISCRCPY
2. Download and select latest scrcpy when it asks for config
3. click START SCRCPY
4. See error in terminal

**Expected behavior**
for scrcpy to start

**Screenshots**
![image](https://github.com/srevinsaju/guiscrcpy/assets/126583428/4316ac21-9187-4366-9097-53d99c866be0)
**ERROR**
```
Traceback (most recent call last):
  File "C:\Users\denis\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\guiscrcpy\launcher.py", line 926, in start_act
    progress = self.progress(progress)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\denis\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\guiscrcpy\launcher.py", line 806, in progress
    self.progressBar.setValue(val)
TypeError: setValue(self, value: int): argument 1 has unexpected type 'float'
```

**Desktop (please complete the following information):**
* [ ] Windows
- **Architecture**: 64-bit
- **Version**: 11

**Additional context**

**Comment by moshpirit** [comment]
Same error in Arch Linux with python 3.11.5 in a dedicated virtual environment.

Steps to reproduce:

```
sudo pacman -S pyenv
git clone https://github.com/pyenv/pyenv-virtualenv.git $(pyenv root)/plugins/pyenv-virtualenv
pyenv install 3.11.5
pyenv virtualenv 3.11.5 my-11.5
pyenv activate my-11.5
pip install guiscrcpy
guiscrcpy
```
