### ISSUE TITLE
NameError: name 'shlex' is not defined

### ISSUE THREAD

**Issue by yochananmarqos** [srevinsaju/guiscrcpy#52]
2.0.post27-65:

```
Traceback (most recent call last):
  File "/usr/sbin/guiscrcpy", line 12, in <module>
    bootstrap()
  File "/usr/lib/python3.8/site-packages/guiscrcpy/launcher.py", line 490, in bootstrap
    bootstrap0()
  File "/usr/lib/python3.8/site-packages/guiscrcpy/launcher.py", line 462, in bootstrap0
    adb.devices(adb.path)
  File "/usr/lib/python3.8/site-packages/guiscrcpy/lib/check.py", line 115, in devices
    proc = Popen(_(increment + " devices"), stdout=PIPE)
  File "/usr/lib/python3.8/site-packages/guiscrcpy/lib/utils.py", line 31, in shellify
    return shlex.split(args)
NameError: name 'shlex' is not defined
```

**Comment by srevinsaju** [comment]
@yochananmarqos thanks for finding this bug, I was about to release v3.0
