### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by Flight-X** [srevinsaju/guiscrcpy#84]
**when i execute the cmd guiscrcpy**
```
2020/04/15 02:27:54.880121 cmd_run.go:893: WARNING: cannot start document portal: write unix @->@/tmp/dbus-QYMdMZnGWx: write: broken pipe
mkdir: cannot create directory '/run/user/0': Permission denied


python3: can't open file '/snap/guiscrcpy/146/guiscrcpy-master/guiscrcpy': [Errno 2] No such file or directory
```

**Comment by srevinsaju** [comment]
@Flight-X How did you install guiscrcpy? Did you install it as a snap?

**Comment by Flight-X** [comment]
yes sir i did it from snap

**Comment by srevinsaju** [comment]
@Flight-X, unfortunately the snap is having a lot of problems and no one is actively working on the snaps. 

Why don't you try:
```bash
pip3 install guiscrcpy --user
```

**Comment by Flight-X** [comment]
yess sir i doing it....

**Comment by Flight-X** [comment]
@srevinsaju 
sir i got this
`ollecting guiscrcpy
  Downloading https://files.pythonhosted.org/packages/e3/1b/1a323892550b3c1914fa6bd4f16419b6c17e8c325243dfe445e42a998285/guiscrcpy-3.5-py3-none-any.whl (1.5MB)
    100% |████████████████████████████████| 1.5MB 252kB/s 
Collecting gitpython (from guiscrcpy)
  Downloading https://files.pythonhosted.org/packages/19/1a/0df85d2bddbca33665d2148173d3281b290ac054b5f50163ea735740ac7b/GitPython-3.1.1-py3-none-any.whl (450kB)
    100% |████████████████████████████████| 460kB 192kB/s 
Collecting fonttools (from guiscrcpy)
  Downloading https://files.pythonhosted.org/packages/c9/81/1b00432d8f5536c09dca00f6f5306be26c477d1c0390a0fb993f8ebf1c64/fonttools-4.7.0-py3-none-any.whl (749kB)
    100% |████████████████████████████████| 757kB 187kB/s 
Collecting PyQt5==5.14.1 (from guiscrcpy)
  Downloading https://files.pythonhosted.org/packages/3a/fb/eb51731f2dc7c22d8e1a63ba88fb702727b324c6352183a32f27f73b8116/PyQt5-5.14.1.tar.gz (3.2MB)
    100% |████████████████████████████████| 3.2MB 225kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-756abdaf/PyQt5/
`

**Comment by srevinsaju** [comment]
@Flight-X are you using Linux or windows? If you are using Linux, which distribution are you using?

**Comment by Flight-X** [comment]
@srevinsaju sir linux mint

**Comment by srevinsaju** [comment]
```
sudo apt install python3-setuptools
```
Please run this, and then try 
```
pip3 install guiscrcpy --user
```

**Comment by Flight-X** [comment]
Now i got this
```
pip3 install guiscrcpy --user
Collecting guiscrcpy
  Downloading https://files.pythonhosted.org/packages/e3/1b/1a323892550b3c1914fa6bd4f16419b6c17e8c325243dfe445e42a998285/guiscrcpy-3.5-py3-none-any.whl (1.5MB)
    100% |████████████████████████████████| 1.5MB 37kB/s 
Collecting PyQt5==5.14.1 (from guiscrcpy)
  Downloading https://files.pythonhosted.org/packages/3a/fb/eb51731f2dc7c22d8e1a63ba88fb702727b324c6352183a32f27f73b8116/PyQt5-5.14.1.tar.gz (3.2MB)
    100% |████████████████████████████████| 3.2MB 19kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-7ca2zsh9/PyQt5/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-7ca2zsh9/PyQt5/

```

**Comment by srevinsaju** [comment]
```
sudo apt install python3-dev python3-wheel
```
and may be try again. 

Thanks, it had never happened to me

**Comment by Flight-X** [comment]
@srevinsaju 
sir 
Now I got this with simple user privileges
pip3 install guiscrcpy --user
```
Collecting guiscrcpy
  Using cached https://files.pythonhosted.org/packages/e3/1b/1a323892550b3c1914fa6bd4f16419b6c17e8c325243dfe445e42a998285/guiscrcpy-3.5-py3-none-any.whl
Collecting gitpython (from guiscrcpy)
  Downloading https://files.pythonhosted.org/packages/19/1a/0df85d2bddbca33665d2148173d3281b290ac054b5f50163ea735740ac7b/GitPython-3.1.1-py3-none-any.whl (450kB)
    100% |████████████████████████████████| 460kB 80kB/s 
Collecting PyQt5==5.14.1 (from guiscrcpy)
  Using cached https://files.pythonhosted.org/packages/3a/fb/eb51731f2dc7c22d8e1a63ba88fb702727b324c6352183a32f27f73b8116/PyQt5-5.14.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-leg31lom/PyQt5/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-leg31lom/PyQt5/

```
With sudo
sudo pip3 install guiscrcpy --user
```
[sudo] password for stelph:           
The directory '/home/stelph/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/stelph/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting guiscrcpy
  Downloading https://files.pythonhosted.org/packages/e3/1b/1a323892550b3c1914fa6bd4f16419b6c17e8c325243dfe445e42a998285/guiscrcpy-3.5-py3-none-any.whl (1.5MB)
    100% |████████████████████████████████| 1.5MB 10kB/s 
Collecting pynput (from guiscrcpy)
  Downloading https://files.pythonhosted.org/packages/33/0a/ea13c055a90b1aff5945e7eb330584f15e5282aead15a8f3cdb977a1534e/pynput-1.6.8-py2.py3-none-any.whl (91kB)
    100% |████████████████████████████████| 92kB 15kB/s 
Collecting fonttools (from guiscrcpy)
  Downloading https://files.pythonhosted.org/packages/c9/81/1b00432d8f5536c09dca00f6f5306be26c477d1c0390a0fb993f8ebf1c64/fonttools-4.7.0-py3-none-any.whl (749kB)
    100% |████████████████████████████████| 757kB 93kB/s 
Requirement already satisfied: psutil in /usr/lib/python3/dist-packages (from guiscrcpy)
Collecting PyQt5==5.14.1 (from guiscrcpy)
  Downloading https://files.pythonhosted.org/packages/3a/fb/eb51731f2dc7c22d8e1a63ba88fb702727b324c6352183a32f27f73b8116/PyQt5-5.14.1.tar.gz (3.2MB)
    100% |████████████████████████████████| 3.2MB 55kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-qd2de5ke/PyQt5/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-qd2de5ke/PyQt5/

```

**Comment by srevinsaju** [comment]
```
pip install --use-wheel guiscrcpy --user
```
I am not sure why this is happening @Flight-X, maybe this will work. Please let me know. You may also like to join discord chat https://discord.gg/RfpWJG

**Comment by espirialo5** [comment]
how can i run the exe in windows 32 bit 😪

**Comment by srevinsaju** [comment]
I have stopped support for 32 bit due to dependency limitations.

**Comment by espirialo5** [comment]
can i know what was the latest version  that supports 32 bit with key mapper

**Comment by espirialo5** [comment]
can i know the latest version that supports 32bit with keymapper

**Comment by srevinsaju** [comment]
@espirialo5 , all the versions support 32-bit if you build it from source, there had not been any user requesting 32 bit for quite long, so I have discontinued support for 32bit. If you would like to run guiscrcpy on 32bit
* Install python from python.org
* Open powershell / Command prompt
* Type 
```bash
pip install guiscrcpy
```
That's it.
It should work on your system then!!
